version: "3.7"
services:
  redis:
    image: redis
    volumes:
      - ./redis_data:/data
    ports:
      - 6379:6379
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    depends_on:
      - redis
    links:
      - redis